### ISSUE TITLE
Builds Fail?

### ISSUE THREAD

**Issue by mattheworres** [ArvinH/atomic-css-search#9]
Looks like in the middle of 2021, Travis CI changed from .org to .com:

![Screenshot 2023-03-15 at 3 02 56 PM](https://user-images.githubusercontent.com/898427/225415959-b2bf7fa3-556a-4560-a735-faef3ba14058.png)

Curious if the project just needs to update those values to fix the project "build" status?

**Comment by ArvinH** [comment]
😅 Thanks @mattheworres and sorry for the late reply...it looks like Travis changed a lot these years and simply changing the link doesn't to the trick.
I'd probably want to move it to GitHub actions if I got time to clean the dust off this repo and give it some updates...with that being said...looks like atomizer has been upgraded to 3.28.x and https://github.com/acss-io/atomizer/tree/main/packages/atomic-css-snippets seems to be a better alternative 🥲
